// <auto-generated />
namespace Internal.Data.SQL.Repository
{
    using System;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Threading.Tasks;
    using Internal.Data.IRepository;

    /// <summary>
    /// Generic repository interface.
    /// </summary>
    /// <typeparam name="T">Class object.</typeparam>
    public class GenericRepository<T> : IGenericRepository<T>
    {
        /// <summary>
        /// Check any record.
        /// </summary>
        /// <param name="where">Where condition.</param>
        /// <returns>true/false.</returns>
        public bool Any(Expression<Func<T, bool>> where = null)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Check any record. Using asynchonous method.
        /// </summary>
        /// <param name="where">Where condition.</param>
        /// <returns>true/false.</returns>
        public Task<bool> AnyAsync(Expression<Func<T, bool>> where = null)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Count any record.
        /// </summary>
        /// <param name="where">Where condition.</param>
        /// <returns>the number of the records.</returns>
        public int Count(Expression<Func<T, bool>> where = null)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Count any record. Using asynchonous method.
        /// </summary>
        /// <param name="where">Where condition.</param>
        /// <returns>the number of the records.</returns>
        public Task<int> CountAsync(Expression<Func<T, bool>> where = null)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Get the first record based on the condition.
        /// </summary>
        /// <param name="where">Where condition.</param>
        /// <returns>The first record, return null if don't have any.</returns>
        public T FirstOrDefault(Expression<Func<T, bool>> where = null)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Get the first record based on the condition.
        /// Using asynchonous method.
        /// </summary>
        /// <param name="where">Where condition.</param>
        /// <returns>The first record, return null if don't have any.</returns>
        public Task<T> FirstOrDefaultAsync(Expression<Func<T, bool>> where = null)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Build a queryable.
        /// </summary>
        /// <returns>IQueryable.</returns>
        public IQueryable<T> Query()
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Get the a single record based on the condition.
        /// </summary>
        /// <param name="where">Where condition.</param>
        /// <returns>The single record, return null if don't have any.</returns>
        public T SingleOrDefault(Expression<Func<T, bool>> where = null)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Get the a single record based on the condition.
        /// Using asynchonous method.
        /// </summary>
        /// <param name="where">Where condition.</param>
        /// <returns>The single record, return null if don't have any.</returns>
        public Task<T> SingleOrDefaultAsync(Expression<Func<T, bool>> where = null)
        {
            throw new NotImplementedException();
        }
    }
}
