// <autogenerated />
namespace BuildEntityModel.File
{
    using System;
    using System.Text;
    using System.Collections.Generic;

    /// <summary>
    /// IFile interface.
    /// </summary>
    public interface IFile
    {
    }

}
