// <autogenerated />
namespace Internal.Authentication.Interface
{
    using Core.Common.Models;
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Threading.Tasks;

    /// <summary>
    /// Authentication interface
    /// </summary>
    public interface IAuthenticationService
    {
        /// <summary>
        /// Login
        /// </summary>
        /// <param name="model">login model</param>
        /// <returns>ResponseModel</returns>
        Task<ResponseModel> Login(LoginModel model);
    }
}
