// <autogenerated />
namespace Internal.DataAccess
{
    using Core.Data.IRepository;
    using Core.IUnitOfWork;
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// Internal Unit Of Work interface
    /// </summary>
    public interface IInternalUnitOfWork : IGenericUnitOfWork
    {
        ITableGenericRepository<User> UserRepository { get; }
    }
}
