// <autogenerated />
namespace Internal.DataAccess
{
    using Core.Data.IRepository;
    using Core.Data.SQL.Repository;
    using Core.IUnitOfWork;
    using Microsoft.EntityFrameworkCore.Storage;
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Threading.Tasks;

    /// <summary>
    /// Internal unit of work
    /// </summary>
    public class InternalUnitOfWork : IInternalUnitOfWork
    {
        /// <summary>
        /// Database context.
        /// </summary>
        private readonly InternalContext context;

        /// <summary>
        /// Transaction object.
        /// </summary>
        private readonly IDbContextTransaction transaction;

        /// <summary>
        /// Initializes a new instance of the <see cref="InternalUnitOfWork"/> class.
        /// Constructor.
        /// </summary>
        /// <param name="context">Internal context.</param>
        public InternalUnitOfWork(InternalContext context)
        {
            this.context = context;
        }

        private ITableGenericRepository<User> userRepository;

        public ITableGenericRepository<User> UserRepository { get { return this.userRepository = this.userRepository ?? new TableGenericRepository<User>(this.context); } }

        public void BeginTransaction()
        {
            throw new NotImplementedException();
        }

        public Task BeginTransactionAsync()
        {
            throw new NotImplementedException();
        }

        public void CommitTransaction()
        {
            throw new NotImplementedException();
        }

        public void RollbackTransaction()
        {
            throw new NotImplementedException();
        }

        public int SaveChanges()
        {
            throw new NotImplementedException();
        }

        public Task<int> SaveChangesAsync()
        {
            throw new NotImplementedException();
        }

        public void Dispose()
        {
            if (this.context != null)
            {
                transaction?.Dispose();
                context.Dispose();
                GC.SuppressFinalize(this);
            }
        }
    }
}
