// <autogenerated />
namespace Core.Common.Enums
{
    /// <summary>
    /// Sort direction
    /// </summary>
    public enum SortDirection
    {
        None = 0,
        Ascending = 1,
        Descending = 2
    }
}
