// <autogenerated />
namespace Core.CommonModels
{
    /// <summary>
    /// Jwt token model.
    /// </summary>
    public class JwtTokenModel
    {
        /// <summary>
        /// Access token.
        /// </summary>
        public string AccessToken { get; set; }

        /// <summary>
        /// Expired time.
        /// </summary>
        public long Expiration { get; set; }

        /// <summary>
        /// Refresh token string
        /// </summary>
        public string RefreshToken { get; set; }

        /// <summary>
        /// User model.
        /// </summary>
        public UserModel UserInfo { get; set; }
    }
}
