// <autogenerated />
namespace BuildEntityModel.Enums
{
    /// <summary>
    /// Constraint enum
    /// </summary>
    public enum SqlConstraintType
    {
        None = 0,
        PrimaryKey = 1,
        ForeignKey = 2,
        Unique = 3,
        Index = 4,
        DefaultValue = 5
    }
}
