// <autogenerated />
namespace Core.Common.Extensions
{
    using System;

    /// <summary>
    /// DateTime extension.
    /// </summary>
    public static class DateTimeExtension
    {
        /// <summary>
        /// Return the bigin time of the day.
        /// </summary>
        /// <param name="date">date value.</param>
        /// <returns>DateTime.</returns>
        public static DateTime BeginOfDay(this DateTime date)
        {
            return new DateTime(date.Year, date.Month, date.Day, 0, 0, 0);
        }

        /// <summary>
        /// Return the end time of the day.
        /// </summary>
        /// <param name="date">date value.</param>
        /// <returns>DateTime.</returns>
        public static DateTime EndOfDay(this DateTime date)
        {
            return new DateTime(date.Year, date.Month, date.Day, 23, 59, 59);
        }
    }
}
