// <autogenerated />
namespace Core.Common.Extensions
{
    using System;
    using System.Linq;
    using System.Reflection;
    using System.Linq.Expressions;
    using System.Collections.Generic;
    using Core.Common.Models;
    using System.Threading.Tasks;
    using Microsoft.EntityFrameworkCore;

    /// <summary>
    /// Entity extension.
    /// </summary>
    public static class EntityExtension
    {

        /// <summary>
        /// Sort object.
        /// </summary>
        /// <typeparam name="T">Object type</typeparam>
        /// <param name="source">Source data.</param>
        /// <param name="sorts">Sort data.</param>
        /// <returns>List object.</returns>
        public static IOrderedQueryable<T> SortBy<T>(this IQueryable<T> source, IList<SortModel> sorts)
        {
            IOrderedQueryable<T> result = null;
            var firstSort = sorts.FirstOrDefault(s => !s.IsMultiOrder);
            if (firstSort == null)
                throw new Exception("Param not valid");

            result = SortBy(source, firstSort);

            foreach (var sort in sorts.Where(s => s.IsMultiOrder))
            {
                result = SortBy<T>(result, sort);
            }
            return result;
        }

        /// <summary>
        /// Sort object.
        /// </summary>
        /// <typeparam name="T">Object type</typeparam>
        /// <param name="source">Source data.</param>
        /// <param name="sorts">Sort data.</param>
        /// <returns>List object.</returns>
        public static IOrderedQueryable<T> SortBy<T>(this IQueryable<T> source, SortModel sort)
        {
            return ApplyOrder<T>(source, sort.Column, sort.LinqDirectionMethod);
        }

        public static IOrderedQueryable<T> OrderBy<T>(this IQueryable<T> source, string property)
        {
            return ApplyOrder<T>(source, property, "OrderBy");
        }

        public static IOrderedQueryable<T> OrderByDescending<T>(this IQueryable<T> source, string property)
        {
            return ApplyOrder<T>(source, property, "OrderByDescending");
        }

        public static IOrderedQueryable<T> ThenBy<T>(this IOrderedQueryable<T> source, string property)
        {
            return ApplyOrder<T>(source, property, "ThenBy");
        }

        public static IOrderedQueryable<T> ThenByDescending<T>(this IOrderedQueryable<T> source, string property)
        {
            return ApplyOrder<T>(source, property, "ThenByDescending");
        }

        private static IOrderedQueryable<T> ApplyOrder<T>(IQueryable<T> source, string property, string methodName)
        {
            string[] props = property.Split('.');
            Type type = typeof(T);
            ParameterExpression arg = Expression.Parameter(type, "x");
            Expression expr = arg;
            foreach (string prop in props)
            {
                // use reflection (not ComponentModel) to mirror LINQ
                PropertyInfo pi = type.GetProperty(prop);
                expr = Expression.Property(expr, pi);
                type = pi.PropertyType;
            }
            Type delegateType = typeof(Func<,>).MakeGenericType(typeof(T), type);
            LambdaExpression lambda = Expression.Lambda(delegateType, expr, arg);

            object result = typeof(Queryable).GetMethods().Single(
                    method => method.Name == methodName
                            && method.IsGenericMethodDefinition
                            && method.GetGenericArguments().Length == 2
                            && method.GetParameters().Length == 2)
                    .MakeGenericMethod(typeof(T), type)
                    .Invoke(null, new object[] { source, lambda });
            return (IOrderedQueryable<T>)result;
        }

        public static async Task<BaseListModel<T>> ToBaseList<T>(this IQueryable<T> source, int? pageIndex, int? pageSize) where T: class
        {
            var result = new BaseListModel<T>();
            if (source != null || source.Any())
            {
                result.TotalItems = await source.CountAsync();

                if (pageIndex.HasValue && pageSize.HasValue && pageSize.Value > 0)
                {
                    var skipCount = (pageIndex.Value - 1) * pageSize.Value;
                    source = source.Skip(skipCount).Take(pageSize.Value);
                }

                result.Items = await source.ToListAsync();
            }

            return result;
        }

        public static async Task<BaseListModel<T>> ToBaseListDistinct<T>(this IQueryable<T> source, int pageIndex, int pageSize) where T: class
        {
            var result = new BaseListModel<T>();
            if (source != null || source.Any())
            {
                result.TotalItems = await source.CountAsync();

                if (pageSize > 0)
                {
                    var skipCount = (pageIndex - 1) * pageSize;
                    source = source.Skip(skipCount).Take(pageSize);
                }

                result.Items = await source.Distinct().ToListAsync();
            }

            return result;
        }
    }
}
