// <autogenerated />
namespace API.Common.Hubs
{
    using System.Security.Claims;
    using Microsoft.AspNetCore.SignalR;

    /// <summary>
    /// Base hub
    /// </summary>
    public class BaseHub : Hub
    {
        /// <summary>
        /// Get current user id
        /// </summary>
        /// <returns></returns>
        protected string CurrentUserId()
        {
            if(Context.User != null && Context.User.Identity.IsAuthenticated)
            {
                var userId = Context.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                return userId;
            }
            return string.Empty;
        }
    }
}
