// <autogenerated />
namespace API.Common.Hubs
{
    using System;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.SignalR;

    /// <summary>
    /// Notification service.
    /// </summary>
    public class NotificationServiceHub : BaseHub
    {
        private readonly ConnectionMapping _connectionMapping;

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="connectionMapping"></param>
        public NotificationServiceHub(ConnectionMapping connectionMapping)
        {
            _connectionMapping = connectionMapping;
        }

        /// <summary>
        /// Connected.
        /// </summary>
        /// <returns></returns>
        public override Task OnConnectedAsync()
        {
            var httpContext = Context.GetHttpContext();
            if (httpContext != null)
            {
                _connectionMapping.Add(CurrentUserId(), Context.ConnectionId);
            }
            return base.OnConnectedAsync();
        }

        /// <summary>
        /// disconected method.
        /// </summary>
        /// <param name="exception">Exception.</param>
        /// <returns></returns>
        public override Task OnDisconnectedAsync(Exception exception)
        {
            var httpContext = Context.GetHttpContext();
            if (httpContext != null)
            {
                _connectionMapping.Remove(CurrentUserId(), Context.ConnectionId);
            }
            return base.OnDisconnectedAsync(exception);
        }
    }
}
