// <autogenerated />
namespace Core.Common.Models
{
    /// <summary>
    /// Paging model
    /// </summary>
    public class PagingDto
    {
        /// <summary>
        /// Page size.
        /// </summary>
        public int PageSize { get; set; }

        /// <summary>
        /// Page index (Current page)
        /// </summary>
        public int PageIndex { get; set; }
    }
}
