// <autogenerated />
namespace Core.Common.Models
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Model response object from the API.
    /// </summary>
    public class ResponseModel
    {
        /// <summary>
        /// Constructor.
        /// </summary>
        public ResponseModel()
        {
            this.Errors = new List<string>();
            this.Extra = new List<object>();
        }

        /// <summary>
        /// Response status code
        /// </summary>
        public Enums.ResponseStatus ResponseStatus { get; set; }

        /// <summary>
        /// List of error or warning string.
        /// </summary>
        public List<string> Errors { get; set; }

        /// <summary>
        /// Result object.
        /// </summary>
        public object Result { get; set; }

        /// <summary>
        /// Extra data response.
        /// </summary>
        public List<object> Extra { get; set; }
    }
}
