// <autogenerated />
namespace Core.Common.Models
{
    using System;
    using System.Text;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using Core.Common.Enums;

    /// <summary>
    /// Sort model.
    /// </summary>
    public class SortModel
    {
        /// <summary>
        /// Property name of column.
        /// </summary>
        public string Column { get; set; }

        /// <summary>
        /// Sort direction.
        /// </summary>
        public SortDirection Direction { get; set; }


        /// <summary>
        /// Allow order by multi column
        /// </summary>
        public bool IsMultiOrder { get; set; } = false;

        [JsonIgnore]
        public string LinqDirectionMethod
        {
            get
            {
                string method = null;
                if (Direction != SortDirection.None)
                {
                    switch (Direction)
                    {
                        case SortDirection.Ascending:
                            {
                                method = !IsMultiOrder ? "OrderBy" : "ThenBy";
                                break;
                            }
                        case SortDirection.Descending:
                            {
                                method = !IsMultiOrder ? "OrderByDescending" : "ThenByDescending";
                                break;
                            }
                    }
                }

                return method;
            }
        }
    }
}
