// <autogenerated />
namespace Core.Common.Models
{
    using System;

    /// <summary>
    /// Token model
    /// </summary>
    public class TokenModel
    {
        /// <summary>
        /// User id
        /// </summary>
        public Guid UserId { get; set; }

        /// <summary>
        /// Token string
        /// </summary>
        public string Token { get; set; }
    }
}
