// <autogenerated />
namespace Internal.Service.Common.Constants
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// Service constant variable class.
    /// </summary>
    public static class ServiceConstant
    {
    }
}
