// <autogenerated />
namespace Core.Common.Services.Constants
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// Service constant variable class.
    /// </summary>
}
