// <auto-generated />
namespace Internal.Data.SQL.TableRepository
{
    using System;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Threading.Tasks;
    using Internal.Data.ITableRepository;
    using Internal.Data.SQL.Repository;

    /// <summary>
    /// Table generic repository interface.
    /// </summary>
    /// <typeparam name="T">Class object.</typeparam>
    public class TableGenericRepository<T> : GenericRepository<T>, ITableGenericRepository<T>
    {
        /// <summary>
        /// Add entity to database.
        /// </summary>
        /// <param name="entity">Entity item.</param>
        public void Add(T entity)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Add entity to database. Using asynchonous method.
        /// </summary>
        /// <param name="entity">Entity item.</param>
        /// <returns>no return.</returns>
        public Task AddAsync(T entity)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Add list of entity to database.
        /// </summary>
        /// <param name="entity">List of entity item.</param>
        public void AddRange(T[] entity)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Add list of entity to database. Using asynchonous method.
        /// </summary>
        /// <param name="entity">List of entity item.</param>
        /// <returns>no return.</returns>
        public Task AddRangeAsync(T[] entity)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Delete entity item.
        /// </summary>
        /// <param name="entity">Entity item.</param>
        public void Delete(T entity)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Delete a list of entity item.
        /// </summary>
        /// <param name="entity">list of entity item.</param>
        public void DeleteRange(T[] entity)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Update entity item.
        /// </summary>
        /// <param name="entity">Entity item.</param>
        public void Update(T entity)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Update entity item. Using asynchonous method.
        /// </summary>
        /// <param name="entity">Entity item.</param>
        public void UpdateAsync(T entity)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Update list of entity item.
        /// </summary>
        /// <param name="entity">List of entity item.</param>
        public void UpdateRange(T[] entity)
        {
            throw new NotImplementedException();
        }
    }
}
