// <autogenerated />
namespace Internal.DataAccess
{
    using System;

    public class User
    {
        public Guid Id { get; set; }
        public Guid EmployeeId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
        public DateTime? LastLogin { get; set; }
        public Guid CreateBy { get; set; }
        public DateTime CreateDate { get; set; }
        public Guid UpdateBy { get; set; }
        public DateTime UpdateDate { get; set; }
        public bool Deleted { get; set; }
        public Guid? DeleteBy { get; set; }
        public DateTime? DeleteDate { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
