// <autogenerated />
namespace BuildEntityModel.Models
{
    using System.Collections.Generic;

    /// <summary>
    /// Table class.
    /// </summary>
    public class Table
    {
        public string TableName { get; set; }
        public List<Column> Columns { get; set; } = new List<Column>();
    }

}
