// <autogenerated />
namespace BuildEntityModel.Models
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    using BuildEntityModel.Enums;

    /// <summary>
    /// Table class.
    /// </summary>
    public class Table
    {
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public string Default { get; set; }
        public bool Nullable { get; set; }
        public string DataType { get; set; }
        public int StringLength { get; set; }
        public int NumericPrecision { get; set; }
        public int NumericScale { get; set; }
        public string Charset { get; set; }
        public EConstraint ConstraintType { get; set; } = EConstraint.None;
        public string ConstraintName { get; set; }
        public string ConstraintValue { get; set; }

    }
}
