// <autogenerated />
namespace BuildEntityModel
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// Contant static class.
    /// </summary>
    public static class Constants
    {
        public static class SqlConstraintType
        {
            public static string Unique = "uniqueidentifier";
            public static string Nvarchar = "nvarchar";
            public static string Varchar = "varchar";
            public static string Text = "text";
            public static string SmallInt = "smallint";
            public static string BigInt = "bigint";
            public static string DateTime = "datetime";
            public static string TimeStamp = "timestamp";
            public static string Bit = "bit";
            public static string Numeric = "numeric";
            public static string Int = "int";
            public static string Decimal = "decimal";
            public static string Float = "float";
            public static string Money = "money";
            public static string TinyInt = "tinyint";
        }
    }
}
