// <autogenerated />
namespace BuildEntityModel
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Text;
    using System.Collections.Generic;

    /// <summary>
    /// Database processing.
    /// </summary>
    public class DatabaseProcessing : IDisposable
    {

        private string ConnectionString = "";
        private string queryString = "";


        List<string> ListTable = new List<string>();

        public DatabaseProcessing(string connectionString)
        {
            ConnectionString = connectionString;
        }

        public DataSet GetListTable()
        {
            DataSet ds = new DataSet();
            try
            {
                using (SqlConnection connection = new SqlConnection(ConnectionString))
                {
                    try
                    {
                        connection.Open();
                        SqlCommand cmd = new SqlCommand("sp_help", connection);
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.Parameters.Add("");
                        SqlDataAdapter da = new SqlDataAdapter(cmd);


                        da.Fill(ds);




                    }
                    catch(Exception ex)
                    {
                        Console.WriteLine(ex);
                    }
                    finally
                    {
                        if(connection.State != ConnectionState.Open)
                        {
                            connection.Close();
                        }
                    }
                }
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex);
            }

            return ds;
        }

        public void GetListTable1()
        {
            try
            {
                using (SqlConnection connection = new SqlConnection(ConnectionString))
                {
                    try
                    {
                        connection.Open();





                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine(ex);
                    }
                    finally
                    {
                        if (connection.State != ConnectionState.Open)
                        {
                            connection.Close();
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
        }

        public void Dispose()
        {
            throw new NotImplementedException();
        }
    }
}
