// <autogenerated />
namespace BuildEntityModel
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    using BuildEntityModel.Models;

    /// <summary>
    /// Generate entity model class.
    /// </summary>
    public class EntityModelProcessing
    {
        private readonly string AutoGenerated = "// <autogenerated />";

        /// <summary>
        /// Processing
        /// </summary>
        /// <param name="tables">list table data</param>
        public void Processing(List<Table> tables)
        {
            try
            {
                foreach (var item in tables)
                {

                }
            }
            catch(Exception ex)
            {
                Console.WriteLine($"Processing {ex.Message}");
            }
        }
    }
}
