// <autogenerated />
namespace BuildEntityModel
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    using BuildEntityModel.Models;
    using BuildEntityModel.File;
    using System.Threading.Tasks;
    using System.Linq;
    using BuildEntityModel.Enums;

    /// <summary>
    /// Generate entity model class.
    /// </summary>
    public class EntityModelProcessing
    {
        private readonly string AutoGenerated = "// <autogenerated />";
        private readonly string namespaceString = "Internal.Data.Security.Entity";

        private readonly IFile _fileCreator;


        /// <summary>
        /// Constructor.
        /// </summary>
        public EntityModelProcessing()
        {
            _fileCreator = new EntityFile();
        }

        /// <summary>
        /// Processing.
        /// </summary>
        /// <param name="tables">list table data</param>
        public async Task Processing(List<Table> tables)
        {
            try
            {
                StringBuilder repositoryBuilder = new StringBuilder();
                StringBuilder modelBuilder = new StringBuilder();

                foreach (var item in tables)
                {
                    await CreateModel(item);

                    repositoryBuilder.AppendLine(await RepositoryBuilder(item.TableName));

                    modelBuilder.AppendLine(await ModelBuilder(item));
                }

                await CreateEntityClass(tables, repositoryBuilder, modelBuilder);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Processing {ex.Message}");
            }
        }

        /// <summary>
        /// Create model class
        /// </summary>
        /// <param name="table">table object.</param>
        private async Task CreateModel(Table table)
        {
            try
            {
                string type = string.Empty;
                StringBuilder fileContent = new StringBuilder();

                fileContent.AppendLine(AutoGenerated);
                fileContent.AppendLine($"namespace {namespaceString}");
                fileContent.AppendLine("{");
                fileContent.AppendLine($"   using System;");
                fileContent.AppendLine($"   ");
                fileContent.AppendLine($"   /// <summary>");
                fileContent.AppendLine($"   /// {table.TableName} entity.");
                fileContent.AppendLine($"   /// </summary>");
                fileContent.AppendLine($"   public class {table.TableName}");
                fileContent.AppendLine("   {");
                foreach (var c in table.Columns)
                {
                    type = string.Empty;
                    switch (c.DataType)
                    {
                        case "nvarchar":
                        case "varchar":
                        case "text":
                            type = "string";
                            break;
                        case "smallint":
                        case "bigint":
                        case "int":
                            type = "int";
                            break;
                        case "datetime":
                        case "timestamp":
                            type = "DateTime";
                            break;
                        case "money":
                        case "decimal":
                            type = "decimal";
                            break;
                        case "numeric":
                        case "float":
                            type = "double";
                            break;
                        case "bit":
                            type = "bool";
                            break;
                        case "tinyint":
                            type = "byte";
                            break;
                        case "uniqueidentifier":
                            type = "Guid";
                            break;
                        default:
                            break;
                    }
                    fileContent.AppendLine("       pubic " + type + CheckNull(c.DataType, c.Nullable) + " " + c.ColumnName + " { get; set; }");
                }
                fileContent.AppendLine("   }");
                fileContent.AppendLine("}");

                await _fileCreator.CreateFile($"{table.TableName}.cs", fileContent.ToString());

            }
            catch (Exception ex)
            {
                Console.WriteLine($"CreateModel {ex.Message}");
            }
        }

        /// <summary>
        /// Create namespace class
        /// </summary>
        /// <param name="table">table object.</param>
        /// <param name="repositoryBuilder">Repository builder object.</param>
        /// <param name="modelMappingBuilder">Model mapping builder.</param>
        private async Task CreateEntityClass(List<Table> table, StringBuilder repositoryBuilder, StringBuilder modelMappingBuilder)
        {
            try
            {
                string fileName = "SecurityContext.cs";
                string type = string.Empty;
                StringBuilder fileContent = new StringBuilder();

                fileContent.AppendLine(AutoGenerated);
                fileContent.AppendLine($"namespace Internal.DataAccess");
                fileContent.AppendLine("{");
                fileContent.AppendLine($"   using System;");
                fileContent.AppendLine($"   using Microsoft.EntityFrameworkCore;");
                fileContent.AppendLine($"   using {namespaceString};");
                fileContent.AppendLine($"   ");
                fileContent.AppendLine($"   /// <summary>");
                fileContent.AppendLine($"   /// Security context.");
                fileContent.AppendLine($"   /// </summary>");
                fileContent.AppendLine($"   public class SecurityContext : DbContext");
                fileContent.AppendLine("   {");
                fileContent.AppendLine($"   ");
                fileContent.AppendLine($"       /// <summary>");
                fileContent.AppendLine($"       /// Constructor method.");
                fileContent.AppendLine($"       /// </summary>");
                fileContent.AppendLine($"       /// <param name=\"options\">DbContextOptions</param>");
                fileContent.AppendLine($"       public SecurityContext(DbContextOptions options): base(options)");
                fileContent.AppendLine("       {");
                fileContent.AppendLine("       }");
                fileContent.AppendLine($"       ");
                fileContent.AppendLine(repositoryBuilder.ToString());
                fileContent.AppendLine($"       /// <summary>");
                fileContent.AppendLine($"       /// Model creating method.");
                fileContent.AppendLine($"       /// </summary>");
                fileContent.AppendLine($"       /// <param name=\"modelBuilder\">ModelBuilder</param>");
                fileContent.AppendLine($"       protected override void OnModelCreating(ModelBuilder modelBuilder)");
                fileContent.AppendLine("       {");
                fileContent.AppendLine($"           modelBuilder.HasAnnotation(\"ProductVersion\", \"2.2.6 - servicing - 10079\");");
                fileContent.AppendLine($"           ");
                foreach (var c in table)
                {
                    fileContent.AppendLine($"            Mapping{c.TableName}Entity(modelBuilder);");
                    fileContent.AppendLine($"           ");
                }
                fileContent.AppendLine("       }");
                fileContent.AppendLine($"       ");
                fileContent.AppendLine(modelMappingBuilder.ToString());

               
                fileContent.AppendLine("   }");
                fileContent.AppendLine("}");

                await _fileCreator.CreateFile(fileName, fileContent.ToString());

            }
            catch (Exception ex)
            {
                Console.WriteLine($"CreateModel {ex.Message}");
            }
        }

        /// <summary>
        /// Create model builder method.
        /// </summary>
        /// <param name="table">table object.</param>
        /// <returns>string</returns>
        private async Task<string> ModelBuilder(Table table)
        {
            try
            {
                await Task.Delay(0);
                string type = string.Empty;
                StringBuilder modelBuilder = new StringBuilder();
                modelBuilder.AppendLine($"      private void Mapping{table.TableName}Entity(ModelBuilder builder)");
                modelBuilder.AppendLine("       {");
                modelBuilder.AppendLine("           builder.Entity<" + table.TableName + ">(entity => {");

                var primaryKeyItem = table.Columns.FirstOrDefault(m => m.ConstraintType == SqlConstraintType.PrimaryKey);
                if (primaryKeyItem != null)
                {
                    modelBuilder.AppendLine($"              entity.HasKey(e => e.{primaryKeyItem.ColumnName}).ForSqlServerIsClustered(true);");
                    modelBuilder.AppendLine(string.Empty);
                }
                foreach (var c in table.Columns)
                {
                    modelBuilder.AppendLine($"              entity.Property(e => e.{c.ColumnName})");
                    modelBuilder.AppendLine("                   .HasColumnName(\"" + c.ColumnName + "\")");
                    modelBuilder.AppendLine("                   .HasColumnType(\"" + c.DataType + "\")");
                    modelBuilder.AppendLine($"                  .IsRequired({c.Nullable})");

                    switch (c.DataType)
                    {
                        case "nvarchar":
                        case "varchar":
                        case "text":
                            modelBuilder.AppendLine($"                  .HasMaxLength({c.StringLength})");
                            break;
                        case "smallint":
                        case "bigint":
                        case "int":
                            break;
                        case "datetime":
                        case "timestamp":
                            break;
                        case "money":
                        case "decimal":
                        case "numeric":
                        case "float":
                            // TODO
                            break;
                        case "bit":
                        case "tinyint":
                        case "uniqueidentifier":
                            break;
                        default:
                            break;
                    }
                    modelBuilder.AppendLine(string.Empty);
                }

                modelBuilder.AppendLine("           });");
                modelBuilder.AppendLine("        }");
                modelBuilder.AppendLine(string.Empty);

                return modelBuilder.ToString();

            }
            catch (Exception ex)
            {
                Console.WriteLine($"ModelBuilder {ex.Message}");
            }
            return string.Empty;
        }

        /// <summary>
        /// Create repository object method.
        /// </summary>
        /// <param name="tableName">table name.</param>
        /// <returns>string</returns>
        private async Task<string> RepositoryBuilder(string tableName)
        {
            await Task.Delay(0);
            return @"       public virtual DbSet<" + tableName + "> " + tableName + "Repository { get; set; }";
        }

        /// <summary>
        /// Get null character based on datatype and nullable status from database.
        /// </summary>
        /// <param name="dataType">Datatype.</param>
        /// <param name="nullable">Status</param>
        /// <returns>return string empty or '?'</returns>
        private string CheckNull(string dataType, bool nullable)
        {
            switch (dataType)
            {
                case "nvarchar":
                case "varchar":
                case "text":
                    return "";
                case "smallint":
                case "bigint":
                case "int":
                case "datetime":
                case "timestamp":
                case "money":
                case "decimal":
                case "numeric":
                case "float":
                case "bit":
                case "tinyint":
                case "uniqueidentifier":
                    if (nullable == true)
                    {
                        return "?";
                    }
                    return "";
                default:
                    return "";
            }
        }
    }
}
