// <auto-generated />
namespace BuildEntityModel
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    using BuildEntityModel.Models;

    /// <summary>
    /// Processing class
    /// </summary>
    public class Processing
    {
        public Processing()
        {

        }

        public void Process()
        {
            try
            {
                DatabaseProcessing dbProcess = new DatabaseProcessing();
                List<Table> listTable = new List<Table>();


                listTable = dbProcess.GetTableInfor();

                if(listTable.Count > 0)
                {
                    EntityModelProcessing modelProcessing = new EntityModelProcessing();
                    modelProcessing.Processing(listTable);
                }
                else
                {
                    Console.WriteLine("Database without table");
                }
            }
            catch(Exception ex)
            {
                Console.WriteLine($"Process {ex.Message}");
            }
        }
    }
}
