// <autogenerated />
namespace BuildEntityModel
{
    using System;

    /// <summary>
    /// Main program.
    /// </summary>
    class Program
    {


        /// <summary>
        /// Main class.
        /// </summary>
        /// <param name="args">srgs object.</param>
        static void Main(string[] args)
        {

            Processing process = new Processing();
            process.Process();
            Console.WriteLine("Process completed");
            Console.ReadLine();
        }
    }
}
