// <autogenerated />
namespace BuildEntityModel
{
    using System;

    /// <summary>
    /// Main program.
    /// </summary>
    class Program
    {

        private string ConnectionString = "";
        private string NameSpace = "";

        /// <summary>
        /// Main class.
        /// </summary>
        /// <param name="args">srgs object.</param>
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
