// <autogenerated />
namespace API.Common.Controllers
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;

    public class BaseController : Controller
    {
        private readonly ILogger<BaseController> _logger;
        public BaseController(IServiceProvider provider)
        {
            //_logger = provider.GetService<ILogger<BaseController>>();
        }
    }
}
