// <autogenerated />
namespace Model.Common
{
    /// <summary>
    /// Jwt token model.
    /// </summary>
    public class JwtTokenModel
    {

        public string AccessToken { get; set; }

        public long Expiration { get; set; }

        public string RefreshToken { get; set; }

        public UserModel UserInfo { get; set; }
    }
}
