// <autogenerated />
namespace Model.Common
{
    using System;
    using System.Text;
    using System.Collections.Generic;

    /// <summary>
    /// Token model
    /// </summary>
    public class TokenModel
    {
        public Guid UserId { get; set; }
        public string Token { get; set; }
    }
}
