// <auto-generated />
namespace Model.Common
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// User model
    /// </summary>
    public class UserModel
    {
        public Guid Id { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string Token { get; set; }
    }
}
